### ISSUE TITLE
`com.amazonaws:aws-java-sdk-s3` is not bundled in version 4.3.8

### ISSUE THREAD

**Issue by boris-petrov** [abashev/vfs-s3#136]
Version 4.3.6 correctly specified `com.amazonaws:aws-java-sdk-s3` as a dependency and when I included `com.github.abashev:vfs-s3:4.3.6` in my Gradle project, all was fine. With version 4.3.8 that's not the case - the AWS JARs are not included and my code doesn't work - I have to add them manually. That's a bug in the release.

**Comment by abashev** [comment]
Thank you so much for your report. It looks like it was broken from the start - I didn't know that classifiers are not working for pom files. I've fixed it with new release and updated documentation accordingly.
