### ISSUE TITLE
Temporary files (/tmp/scalr.*.s3)

### ISSUE THREAD

**Issue by robmoore** [abashev/vfs-s3#20]
We're using the vfs-s3 library and are seeing a large number of files in the temp directory following the form of scalr.*.s3 that appear to be created by the vfs-s3 code and are never cleaned up. Looking at the code for S3FileObject, it appears these are cache files (see getCacheFileChannel()) created using File.createTempFile(). Our application runs for an extended period of time so these files will not be removed as the VM isn't shut down. It might be worth utilizing something like org.apache.commons.io.FileCleaner which provides a way to clean up files when GC occurs.

**Comment by robmoore** [comment]
Actually, the reference I made should be to FileCleanerTracker (http://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FileCleaningTracker.html) as FileCleaner has been deprecated.

**Comment by robmoore** [comment]
It looks like this may be an issue with our failing to close the files after using them. It might be useful to provide some direction in terms of usage that spells out the need to do so.

**Comment by abashev** [comment]
Rob, so do you think we don't need this file tracker and it was your issue?

**Comment by robmoore** [comment]
I believe so but haven't tested it yet. Reviewing the vfs-s3 code, it looks
like closing the file will cause doDetach() in the S3FileObject class which
will let go of the cached files we're seeing.

**Comment by robmoore** [comment]
Closing the file fixed the issue so closing.
