### ISSUE TITLE
Can't use custom AmazonS3Client

### ISSUE THREAD

**Issue by abrooksv** [abashev/vfs-s3#30]
You can not manually create the AmazonS3Client and set it on the configuration without also setting credentials. If you already configured the client, then the credentials should not be required.

I'd advise moving https://github.com/abashev/vfs-s3/blob/branch-2.3.x/src/main/java/com/intridea/io/vfs/provider/s3/S3FileProvider.java#L78 down into the "if(service == null)" block.

**Comment by abashev** [comment]
Fixed

https://github.com/abashev/vfs-s3/commit/601715615e90bd68bd8b4f5d88497febe3a4ebc0
