### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by ptahchiev** [abashev/vfs-s3#33]
I get this error when I try to list a file in my bucket:

```
ERROR: Cannot load image: /solarapparel/content/banner/solar-your-better-half.png because of Unknown message with code "Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 13180FE7FC5D411F)"
```

When I try to open the bucket with `S3Browser` I get the following error:

```
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256
```

According to this: http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4
the Frankfurt region only supports the V4 method of authentication. Please make sure the vfs-s3 supports the V4 too.

**Comment by cbandy** [comment]
Looks like a single function call may resolve: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#specify-signature-version

**Comment by abashev** [comment]
Fixed with new AWS SDK
