### ISSUE TITLE
Upgrade to org.apache.commons:commons-vfs2:2.1

### ISSUE THREAD

**Issue by ptahchiev** [abashev/vfs-s3#37]
As per the last comment in this issue:

https://issues.apache.org/jira/browse/VFS-574

commons-vfs2 2.1 is out and has more than 171 bugfixes. Please use the latest version from the maven central repository.

**Comment by abashev** [comment]
Yes, with 2.4.0 I'm using latest snapshot of 2.1 version

**Comment by ptahchiev** [comment]
Yes, I see.. but why a snapshot?!

**Comment by abashev** [comment]
@ptahchiev sorry, it is not snapshot - it is repository clone from tag 2.1. All sources should be the same as version 2.1 but have build by me.
