### ISSUE TITLE
Upgrade to aws-sdk-java-v2

### ISSUE THREAD

**Issue by ptahchiev** [abashev/vfs-s3#46]
https://github.com/aws/aws-sdk-java-v2

**Comment by ptahchiev** [comment]
Any chance to have this included in 2.4.3?

**Comment by abashev** [comment]
Nope, I've changed a lot of things and want to spend all efforts on the new version - if you have strong demand for 2.x + AWS v2 then you can do PR or hire me.

**Comment by abashev** [comment]
Not relevant anymore because 4.1.0 is self-contained.
