### ISSUE TITLE
Vfs-S3 v3.0 is not available for download

### ISSUE THREAD

**Issue by sergey-derugo** [abashev/vfs-s3#49]
According to https://github.com/abashev/vfs-s3 the VFS plugin v3.0 should be available in the repository http://dl.bintray.com/content/abashev/vfs-s3 but currently it is not available there

**Comment by sergey-derugo** [comment]
The latest build https://travis-ci.org/abashev/vfs-s3 is not successful due to numerous "_com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region._" in the unit tests. Very good explanation is here http://opensourceforgeeks.blogspot.com/2018/07/how-to-fix-unable-to-find-region-via.html

Possible solution is set env variable **AWS_REGION** or define region in the .**aws/config**.
 Could you please adjust the configuration of the Travis? If modification of **travis.yml** is needed then could you please provide the details which region should be used to access the bucket **s3-tests**?

**Comment by abashev** [comment]
@sergey-derugo I almost finished huge refactoring that I've planned to version 3.x. I thought to keep it as a bunch of commits on my machine till I finish tests but it looks like it has strong demand from the community ☺️ So I pushed everything to the repo and looking for your comments.
I totally refactored a way how vfs-s3 were configured and how all urls were processed. From now all buckets should syntax from AWS SDK https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#bucket-config-options-intro It could be virtual-hosted-style or path-based style but it any case it should contains a region. That will solve your issue with regions
