### ISSUE TITLE
What are the concurrency issues that were fixed?

### ISSUE THREAD

**Issue by boris-petrov** [abashev/vfs-s3#52]
It says in the README:

```
Please be aware that vfs-s3 is using custom build of commons-vfs2. It works in the same way as original commons-vfs2 but it was patched to fix some concurrency issues.
```

Which were those concurrency issues and why don't you create a pull-request in the main repo so that they can be fixed upstream? That way all users of VFS could benefit from them. :)

**Comment by abashev** [comment]
I'll try one more time but my previous attempt has failed. Maybe these days, they will be more collaborative.

**Comment by boris-petrov** [comment]
@abashev - yes, they are very slow, but at least at some point they do merge PRs, so just open one and one day we'll all be happy users of the fixes. :) Thanks!
