### ISSUE TITLE
us-east-1 is hardcoded and no other region works

### ISSUE THREAD

**Issue by boris-petrov** [abashev/vfs-s3#55]
```
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: ...; S3 Extended Request ID: ...)
```

When I have `s3://s3.eu-central-1.amazonaws.com/bucket-name` as a URL. I believe the issue is [here](https://github.com/abashev/vfs-s3/blob/8255cad0f083bb16352320b03fd5efac110bbc9c/src/main/java/com/github/vfss3/S3FileProvider.java#L83).

Also, is there any way to make `vfs-s3` work with the original VFS code not your patched one? As we depend on their latest fixes...

**Comment by abashev** [comment]
We have a test for that https://github.com/abashev/vfs-s3/blob/branch-3.0.x/src/test/java/com/github/vfss3/S3FileNameParserTest.java#L22

But I'll check. Maybe do you have more information on how to reproduce it?

**Comment by boris-petrov** [comment]
Well, just create a bucket in a region other than us-east-1 and try connecting to it. It will blow up.

I changed the hardcoded string that I sent a link to to our region and it started working. You can blame the line to see which commit changed it.

**Comment by boris-petrov** [comment]
I think this is working with the latest commit so I'll leave you to close the issue when you please. Thanks for the support!
