### ISSUE TITLE
Update the aws-java-sdk-s3 library

### ISSUE THREAD

**Issue by pierre-leonard** [abashev/vfs-s3#64]
looks like (at least) eu-north-1 is missing from it

**Comment by svella** [comment]
FWIW - until it is updated, it is possible to use regions the SDK doesn't know about by setting the endpoint rather than the region. Another possibility is to to configure your build system to ignore the sdk dependency from vfs-s3 and explicitly pull in the version you want.

**Comment by abashev** [comment]
Fixed in 4.1.0
