### ISSUE TITLE
Not all classes from aws-java-sdk-s3 are shadowed

### ISSUE THREAD

**Issue by boris-petrov** [abashev/vfs-s3#65]
Some classes in the `com.amazonaws` package are not "shaded". This means that when I also import `aws-java-sdk-s3` to use it in my own code, the loading of these classes is non-deterministic and runtime exceptions occur because of incompatible classes.

Either *all* classes from `aws-java-sdk-s3` should be "shaded" or it should be used as a dependency (of course, that leads to issues like https://github.com/abashev/vfs-s3/issues/64).

P.S. I'm talking about `vfs-s3` version 4.2.0.

**Comment by skarzhevskyy** [comment]
Ideally there can be two artefacts with aws-sdk-shaded and vfs-s3 that have project classes only

**Comment by abashev** [comment]
From now we have the raw artifact and `with-aws-sdk` classifier.
