### ISSUE TITLE
Incorrect S3 metadata for content type, last accessed time and content length.

### ISSUE THREAD

**Issue by deyant** [abashev/vfs-s3#68]
All uploaded files have content-type = application/octet-stream. Mime type is not properly set before uploading in ObjectMetadataHolder. 

A quick patch fixes the problem, see attached file. 

[Use_correct_ObjectMetadata_instance_in_withContentType,_withLastModifiedNow_and_withConten.patch.zip](https://github.com/abashev/vfs-s3/files/4936305/Use_correct_ObjectMetadata_instance_in_withContentType._withLastModifiedNow_and_withConten.patch.zip)

**Comment by abashev** [comment]
@deyant could you please post it as PR?
