### ISSUE TITLE
Any know if this is hosted on a public maven repo?

### ISSUE THREAD

**Issue by epugh** [abashev/vfs-s3#7]
Don't want to import this entire project just to compile it.

**Comment by abashev** [comment]
I have bintray account and after a feedback from someone I will release stable version :)

**Comment by epugh** [comment]
Interesting service....    Look forward to trying it out.  I am using the code to list our directories of files in S3 and populate a SQS queue.  Will let you know how it goes!

Eric

On Feb 11, 2013, at 4:18 PM, Alexey Abashev wrote:

> bintray

---

Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com
Co-Author: Apache Solr 3 Enterprise Search Server available from http://www.packtpub.com/apache-solr-3-enterprise-search-server/book  
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.
