### ISSUE TITLE
S3FileObject upload throws NPE when validating md5

### ISSUE THREAD

**Issue by tatiananovik** [abashev/vfs-s3#83]
When uploading file to S3, getETag() returns null, so md5 is also null. This happens [here](https://github.com/abashev/vfs-s3/blob/branch-4.x.x/src/main/java/com/github/vfss3/S3FileObject.java#L887).

NullPointerException is thrown during MD5 verification check:
```
java.lang.NullPointerException
	at com.github.vfss3.S3FileObject.upload(S3FileObject.java:911)
	at com.github.vfss3.S3FileObject.doCopyFrom(S3FileObject.java:818)
	at com.github.vfss3.S3FileObject.copyFrom(S3FileObject.java:722)
```

**Comment by cy6erskunk** [comment]
Hello, do you have any plans to release the fix for the issue? It would be appreciated a lot as it will allow us to upgrade to a version where https://github.com/abashev/vfs-s3/issues/70 is fixed.
Thank you!
